FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY schemas/ /app/schemas/
COPY src/consumer_vuelos /app/src/consumer_vuelos

CMD ["python", "src/consumer_vuelos/dic_rutas.py"]